package com.company;

public enum  TokenType {
    USE,CREATE,DROP,ALTER,INSERT,SELECT,UPDATE,DELETE,JOIN,LEFTPARENTHESIS,RIGHTPARENTHESIS,SEMICOLON,COMMA
    ,AND,OR,MULTIPLY,UNKNOWN,TABLE,DATABASE,VALUE,SPACE,VALUES,WHERE,FROM,LIKE,GREATER,LESS,EQUAL,GREATEREQUAL,
    LESSEQUAL,NOTEQUAL,INTO
}
